matrix:
  include:
    - language: node_js
      node_js: '14.3.0'
      services:
          - docker
      cache:
        directories:
          - 'client/node_modules'
      before_script:
        - npm install -g @angular/cli@9.1.9
      script:
        - cd client/
        - npm install
        - npm run build
        - docker build .
