language: node_js

node_js:
    - "14"

dist: trusty

services:
    - docker

cache:
    directories:
        - "BackEnd/node_modules"
        - "client/node_modules"

before_script:
    - npm install -g @angular/cli@9.1.7
    - npm install -g eslint

script:
    - cd ./BackEnd
    - npm run lint
    - cd ../client
    - npm install
    - npm run lint
    - npm run build
    - cd ..
    - mv example.env .env
    - docker-compose build
