version: "2.3"
services:
  pb-client:
    image: jgkawell/power-budget-client:latest
    container_name: pb-client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - CLIENT_PORT=${CLIENT_PORT}
        - API_BASE_URL=${API_BASE_URL}
        - API_PORT=${API_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
  pb-api:
    image: jgkawell/power-budget-api:latest
    container_name: pb-api
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      pb-database:
        condition: service_healthy
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_PORT=${API_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  pb-database:
    image: jgkawell/power-budget-database:latest
    container_name: pb-database
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DATABASE}
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

# If you're using swag as a reverse proxy
# networks:
#   default:
#     external:
#       name: swag