version: "2.3"
services:
  frontend:
    image: jgkawell/power-budget-frontend:latest
    container_name: frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_BASE_URL=${BACKEND_BASE_URL}
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  backend:
    image: jgkawell/power-budget-backend:latest
    container_name: backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - BACKEND_PORT=${BACKEND_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  database:
    image: jgkawell/power-budget-database:latest
    container_name: database
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./Database/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

# If you're using swag as a reverse proxy
# networks:
#   default:
#     external:
#       name: swag