version: "3"
services:
  client:
    image: jgkawell/power-budget-client:latest
    container_name: pb-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
  api:
    image: jgkawell/power-budget-api:latest
    container_name: pb-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - API_ENV=${API_ENV}
      - API_LOG_LEVEL=${API_LOG_LEVEL}
      - API_VERSION=${API_VERSION}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  database:
    image: jgkawell/power-budget-database:latest
    container_name: pb-database
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DATABASE}
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data

# If you're using swag as a reverse proxy
# networks:
#   default:
#     external:
#       name: swag