name: API Local CI

defaults:
  run:
    working-directory: api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint ./...

      - name: Download and verify
        run: |
          go mod download
          go mod verify

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build
